name: DockerBase build and push

on:
  push:
    tags:
      - 'base*'

jobs:
  docker:

    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/Dockerfile_base
            image: denglab/vpfkit_base
    
    permissions:
      contents: read
      packages: write

    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3

      # Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerHub Login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
