name: Docker

on:
  push:
    tags:
      - 'v*'
      - 'd*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - dockerfile: ./container/phispy/Dockerfile
          #   image: jinlongru/phispy
          # - dockerfile: ./container/viroprofiler_base/Dockerfile
          #   image: jinlongru/viroprofiler_base
          # - dockerfile: ./container/viroprofiler_binning/Dockerfile
          #   image: jinlongru/viroprofiler_binning
          # - dockerfile: ./container/viroprofiler_geneannot/Dockerfile
          #   image: jinlongru/viroprofiler_geneannot
          # - dockerfile: ./container/viroprofiler_host/Dockerfile
          #   image: jinlongru/viroprofiler_host
          # - dockerfile: ./container/viroprofiler_replicyc/Dockerfile
          #   image: jinlongru/viroprofiler_replicyc
          - dockerfile: ./Dockerfile
            image: jinlongru/viroprofiler-viewer
          # - dockerfile: ./container/protologger/Dockerfile
          #   image: jinlongru/protologger
          # - dockerfile: ./Dockerfile
          #   image: jinlongru/phagetk
          # - dockerfile: ./docker/vpfbase/Dockerfile
          #   image: jinlongru/vpfbase
          # - dockerfile: ./docker/iphop/Dockerfile
          #   image: jinlongru/iphop
          # - dockerfile: ./docker/bacphlip/Dockerfile
          #   image: jinlongru/bacphlip
          # - dockerfile: ./container/flye/Dockerfile
          #   image: jinlongru/flye
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: "."
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}